### ISSUE TITLE
Bootstrap failure in EMR

### ISSUE THREAD

**Issue by Ghoul-SSZ** [aws-samples/emr-trino-autoscale#2]
EMR bootstrap fails when running the `emr-install_autoscale.sh` script.
Tested on EMR version 6.9.0 and 6.11.0.

EMR Error log: 
```
chmod: cannot access ‘/emr/metricscollector/isbusy’: No such file or directory
Created symlink from /etc/systemd/system/multi-user.target.wants/trino-autoscale.service to /etc/systemd/system/trino-autoscale.service.
Job for trino-autoscale.service failed because the control process exited with error code. See "systemctl status trino-autoscale.service" and "journalctl -xe" for details.

```

What is this "/emr/metricscollector/isbusy" ? Any idea on how to fix this issue?

UPDATE:
1. When commenting out that one line. Bootstrap still fails, but with a slightly different error log:
```
Created symlink from /etc/systemd/system/multi-user.target.wants/trino-autoscale.service to /etc/systemd/system/trino-autoscale.service.
Job for trino-autoscale.service failed because the control process exited with error code. See "systemctl status trino-autoscale.service" and "journalctl -xe" for details.
```
2. When spinning up the EMR cluster without the bootstrap script, and then run it once the cluster is available, the script runs fine. see log below:
```
[hadoop@ip-xxx-xx-xx-xxx ~]$ ./test.sh xx-xx-emr-trino-autoscale
download: s3://xx-xx-emr-trino-autoscale/artifacts/aws-emr-trino-autoscaling/trino-autoscale.jar to ../../opt/trino-autoscale/trino-autoscale.jar
chmod: cannot access '/emr/metricscollector/isbusy': No such file or directory
Created symlink from /etc/systemd/system/multi-user.target.wants/trino-autoscale.service to /etc/systemd/system/trino-autoscale.service.
[hadoop@ip-xxx-xx-xx-xxx ~]$ systemctl status trino-autoscale.service
● trino-autoscale.service - Trino-Autoscale
   Loaded: loaded (/etc/systemd/system/trino-autoscale.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2023-07-18 13:28:54 UTC; 12s ago
  Process: 9077 ExecStart=/usr/bin/trino-autoscale (code=exited, status=0/SUCCESS)
 Main PID: 9121 (java)
    Tasks: 26
   Memory: 240.4M
   CGroup: /system.slice/trino-autoscale.service
           └─9121 /etc/alternatives/jre/bin/java -Xmx1024m -XX:+ExitOnOutOfMemoryError -XX:MinHeapFreeRatio=10 -server -cp /opt/trino-autoscale/trino-autoscale.jar com.ama...

```

**Comment by ripani-aws** [comment]
Hi Steven, thanks for reporting this. About the file `/emr/metricscollector/isbusy` this is a file that is used internally by EMR to support auto-termination policy. You can read more about this feature [here](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-auto-termination-policy.html). 

About the installation failure, you don't need to run the script as an EMR Bootstrap Action, and you can simply submit the script as an [EMR Step](https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-commandrunner.html#emr-commandrunner-examples). You shouldn't install this utility using a Bootstrap Action, because in that case the utility will be installed on all the nodes of the cluster, which might cause you issues if the utility is running on all the nodes at the same time.

**Comment by Ghoul-SSZ** [comment]
Ahh ok! I will try it out, thanks!
